const $=id=>document.getElementById(id),S=new THREE.Scene();S.background=new THREE.Color(0x76553f);S.fog=new THREE.Fog(0x76553f,30,65);
const R=new THREE.WebGLRenderer({canvas:$('c'),antialias:true,powerPreference:'high-performance'});R.setPixelRatio(Math.min(devicePixelRatio,1.5));R.setSize(innerWidth,innerHeight);R.shadowMap.enabled=true;
const C=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,100);C.position.set(10,13,15);
S.add(new THREE.HemisphereLight(0xffe4c0,0x302019,2));const L=new THREE.DirectionalLight(0xffd2a0,3);L.position.set(-10,20,8);L.castShadow=true;L.shadow.mapSize.set(1024,1024);S.add(L);
const M={floor:new THREE.MeshStandardMaterial({color:0x777067,roughness:.8}),wall:new THREE.MeshStandardMaterial({color:0x493027}),wood:new THREE.MeshStandardMaterial({color:0x92572d}),metal:new THREE.MeshStandardMaterial({color:0x9ba1a2,metalness:.65,roughness:.3}),red:new THREE.MeshStandardMaterial({color:0x8d3530}),cream:new THREE.MeshStandardMaterial({color:0xe6d1b1}),green:new THREE.MeshStandardMaterial({color:0x41634d}),gold:new THREE.MeshStandardMaterial({color:0xd49b36,metalness:.5})};
function box(x,y,z,m,a=0,b=0,d=0){let q=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),m);q.position.set(a,b,d);q.castShadow=q.receiveShadow=true;S.add(q);return q}function cyl(r,h,m,a,b,d){let q=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,16),m);q.position.set(a,b,d);q.castShadow=q.receiveShadow=true;S.add(q);return q}
box(28,.3,22,M.floor,0,-.15,0);box(28,5,.3,M.wall,0,2.5,-11);box(.3,5,22,M.wall,-14,2.5,0);box(.3,5,22,M.wall,14,2.5,0);box(28,5,.3,M.wall,0,2.5,11);
const tables=[];function table(x,z){let g=new THREE.Group(),t=new THREE.Mesh(new THREE.CylinderGeometry(1.1,.9,.2,24),M.wood);t.position.y=1.05;g.add(t);cyl(.16,1,M.metal,x,.5,z);for(let i=0;i<4;i++){let a=i*Math.PI/2;box(.8,.18,.8,M.red,x+Math.cos(a)*1.55,.55,z+Math.sin(a)*1.55)}g.position.set(x,0,z);S.add(g);tables.push({x:x,z:z,busy:false})}[-8,-3,3,8].forEach(x=>table(x,-5));[-8,-3,3,8].forEach(x=>table(x,1));
const stations=[['🍕',-9,6],['🍔',-4,6],['🍝',1,6],['🍟',6,6],['🥤',10,6]];stations.forEach(v=>{box(2.2,1.2,1.2,M.metal,v[1],.6,v[2]);box(1.6,.3,.8,M.wood,v[1],1.35,v[2])});
box(10,1,1,M.wood,3,.5,9);box(2,2.5,1,M.wall,9,1.25,9.8);cyl(.55,1.5,M.metal,11,.75,8);
const P=new THREE.Group();S.add(P);let body=new THREE.Mesh(new THREE.CylinderGeometry(.45,.5,1.1,12),M.cream);body.position.y=1.1;P.add(body);let head=new THREE.Mesh(new THREE.SphereGeometry(.35,14,10),M.cream);head.position.y=1.9;P.add(head);let hat=new THREE.Mesh(new THREE.CylinderGeometry(.45,.35,.3,16),M.cream);hat.position.y=2.3;P.add(hat);box(.7,.9,.1,M.green,0,1.1,.4);P.position.set(0,0,4);
const recipes=[['המבורגר','🍔',18,3],['פיצה','🍕',22,4],['פסטה','🍝',20,4],['סלט','🥗',14,2],['עוף','🍗',26,5],['נקניקייה','🌭',15,2],['סנדוויץ׳','🥪',16,2],['צ׳יפס','🍟',12,2],['מרק','🍲',19,3],['פנקייק','🥞',17,3],['עוגה','🍰',28,6],['גלידה','🍦',13,2]],people=[];let money=8420,xp=0,lvl=1,cook=null,joy={x:0,y:0,on:false};try{let s=JSON.parse(localStorage.getItem('bc')||'null');if(s){money=s.money;xp=s.xp;lvl=s.lvl}}catch{}
function save(){localStorage.setItem('bc',JSON.stringify({money:money,xp:xp,lvl:lvl}))}function xpadd(n){xp+=n;while(xp>=lvl*100){xp-=lvl*100;lvl++;alert('עלית רמה!')}$('xp').textContent=xp;$('lvl').textContent=lvl;save()}function cash(n){money+=n;$('money').textContent=Math.floor(money).toLocaleString('he-IL');save()}
function npc(){if(people.length>8)return;let g=new THREE.Group(),col=[0x3170aa,0xa83d47,0x4c7c4c,0x8b603d,0x72518b,0xc58d3d][Math.floor(Math.random()*6)],b=new THREE.Mesh(new THREE.CylinderGeometry(.37,.42,.85,12),new THREE.MeshStandardMaterial({color:col}));b.position.y=.9;g.add(b);let h=new THREE.Mesh(new THREE.SphereGeometry(.29,12,9),M.cream);h.position.y=1.7;g.add(h);S.add(g);let r=recipes[Math.floor(Math.random()*recipes.length)],c={g:g,r:r,state:0,t:null,wait:45};g.position.set((Math.random()-.5)*8,0,-15);people.push(c)}
function move(c,x,z,s=.04){let dx=x-c.g.position.x,dz=z-c.g.position.z,d=Math.hypot(dx,dz)||1;c.g.position.x+=dx/d*s;c.g.position.z+=dz/d*s;c.g.rotation.y=Math.atan2(dx,dz)}
function act(){let a=$('actions');a.innerHTML='';if(cook===null){let st=stations.find(v=>Math.hypot(P.position.x-v[1],P.position.z-v[2])<2.4);if(st){let b=document.createElement('button');b.className='act';b.innerHTML=st[0]+'<small>בשל</small>';b.onclick=()=>{let r=recipes[Math.floor(Math.random()*recipes.length)];cook={r:r,end:performance.now()+r[3]*1000};};a.appendChild(b)}}let c=people.find(v=>v.state===2&&Math.hypot(P.position.x-v.g.position.x,P.position.z-v.g.position.z)<2.4);if(c){let b=document.createElement('button');b.className='act';b.innerHTML='🍽<small>הגש</small>';b.onclick=()=>{if(cook){c.state=3;cook=null;xpadd(8)}};a.appendChild(b)}}
function npcUpdate(c,dt){if(c.state===0){move(c,0,-7);if(c.g.position.z>-8)c.state=1}else if(c.state===1){if(!c.t)c.t=tables.find(t=>!t.busy);if(!c.t){move(c,0,-7);return}c.t.busy=true;move(c,c.t.x,c.t.z);if(Math.hypot(c.g.position.x-c.t.x,c.g.position.z-c.t.z)<.35){c.state=2;c.wait=45}}else if(c.state===2){c.wait-=dt;if(c.wait<=0){c.state=4;c.t.busy=false}}else if(c.state===3){setTimeout(()=>{if(c.state===3){c.state=5;c.t.busy=false}},5000)}else if(c.state===4){move(c,0,-15);if(c.g.position.z<-13){S.remove(c.g);people.splice(people.indexOf(c),1)}}else if(c.state===5){cash(c.r[2]);xpadd(12);c.state=4}}
let last=performance.now(),spawn=0;function loop(now){requestAnimationFrame(loop);let dt=Math.min(.05,(now-last)/1000);last=now;if(joy.on){P.position.x+=joy.x*.14;P.position.z+=joy.y*.14;P.rotation.y=Math.atan2(joy.x,joy.y)}P.position.x=THREE.MathUtils.clamp(P.position.x,-12,12);P.position.z=THREE.MathUtils.clamp(P.position.z,-8,9);C.position.x=THREE.MathUtils.lerp(C.position.x,P.position.x+10,dt*3);C.position.z=THREE.MathUtils.lerp(C.position.z,P.position.z+13,dt*3);C.lookAt(P.position.x,0,P.position.z);spawn-=dt;if(spawn<=0){npc();spawn=5}people.slice().forEach(c=>npcUpdate(c,dt));if(cook&&now>=cook.end)cook=null;act();R.render(S,C)}
let je=$('joy'),js=je.querySelector('i');je.onpointerdown=e=>{joy.on=true;je.setPointerCapture(e.pointerId)};je.onpointermove=e=>{if(!joy.on)return;let r=je.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,m=50,d=Math.hypot(x,y)||1;if(d>m){x=x/d*m;y=y/d*m}joy.x=x/m;joy.y=y/m;js.style.transform='translate('+x+'px,'+y+'px)'};je.onpointerup=()=>{joy.on=false;joy.x=joy.y=0;js.style.transform=''};
function panel(k){let p=$('panel');p.style.display='block';let h='<button class="close" onclick="panelClose()">✕</button>';if(k==='orders'){h+='<h2>📋 הזמנות</h2>';people.forEach(c=>h+='<div class="card">'+c.r[1]+' '+c.r[0]+' — '+Math.max(0,Math.ceil(c.wait))+' שניות</div>')}else if(k==='up'){h+='<h2>⬆️ שדרוגים</h2>';['מהירות בישול','מהירות הליכה','מחיר מנות','סבלנות','שולחנות','מטבח'].forEach((n,i)=>h+='<div class="card"><b>'+n+'</b><button class="buy" onclick="buy('+((i+1)*100)+')">'+((i+1)*100)+' ₪</button></div>')}else if(k==='staff'){h+='<h2>👥 צוות</h2><div class="card">👨‍🍳 טבח <button class="buy" onclick="buy(900)">900 ₪</button></div><div class="card">🧹 מנקה <button class="buy" onclick="buy(700)">700 ₪</button></div><div class="card">🧾 מלצר <button class="buy" onclick="buy(1100)">1100 ₪</button></div>')}else h+='<h2>🍴 המסעדה</h2><div class="card">⭐ דירוג 4.8<br>8 שולחנות · 5 תחנות מטבח<br>משימות: הגש 5 מנות, הרווח 500 ₪</div>';p.innerHTML=h}window.panelClose=()=>{$('panel').style.display='none'};window.buy=n=>{if(money<n)return;money-=n;$('money').textContent=Math.floor(money);save();panel('up')};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>panel(b.dataset.p));$('money').textContent=Math.floor(money).toLocaleString('he-IL');$('xp').textContent=xp;$('lvl').textContent=lvl;requestAnimationFrame(loop);